### ISSUE TITLE
Exception in console log when VS Code open (with no workspace or file)

### ISSUE THREAD

**Issue by yegor-mialyk** [ppatotski/vscode-commandbar#83]
I got the following exception in console log (in Developer Tools) whenever I open VS Code with no workspace, folder or file opened:

console.ts:134 [Extension Host] TypeError: Cannot read property 'length' of undefined	at getWorkspaceFolder (C:\Users\Yegor\.vscode\extensions\gsppvo.vscode-commandbar-0.3.1\extension.js:90:43)	at activate (C:\Users\Yegor\.vscode\extensions\gsppvo.vscode-commandbar-0.3.1\extension.js:416:29)	at Function._callActivateOptional (c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:748:518)	at Function._callActivate (c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:748:207)	at define._doActivateExtension.Promise.all.then.e (c:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:747:245)

--------
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by lonix1** [comment]
This also happens when debugging extensions.
